### ISSUE TITLE
Setting min_seq_len in PytorchDatasetConfig to < 2 with task dataframes leads to keyerror

### ISSUE THREAD

**Issue by juancq** [mmcdermott/EventStreamGPT#109]
Setting min_seq_len to < 2 in PytorchDatasetConfig with task dataframes leads to keyerror here: 
https://github.com/mmcdermott/EventStreamGPT/blob/2f433a695112fdccb7b28a50cb44b6f39fce4349/EventStream/data/pytorch_dataset.py#L464

```bash
KeyError: 1717150
```

where 1717150 is a valid key in DL_shards.json.

**Comment by mmcdermott** [comment]
@juancq just re-read the title of this one. Is there a typo in the detailed description (should it be `min_seq_len`)? I'll presume so given the title and look into this.

**Comment by juancq** [comment]
@mmcdermott You are right, I made a spelling mistake in the detailed description. It should be min_seq_len.

**Comment by juancq** [comment]
I have moved on to another dataset, and I have not encountered this bug again. I'm happy to close this for now and reopen if I encounter it again.

**Comment by mmcdermott** [comment]
Sounds good, thank you!
