### ISSUE TITLE
Setting maximum number of threads Polars will use

### ISSUE THREAD

**Issue by juancq** [mmcdermott/EventStreamGPT#47]
On a machine with 16GB of memory and 4 cores, I had to manually set the maximum number of threads Polars used to 1, otherwise the build dataset script kept crashing due to a memory allocation error (I do not have further details as to where it crashed). Setting number of threads to 1 allowed the build_dataset script to run to completion (following the example here: https://www.rhosignal.com/posts/streaming-chunk-sizes/). It would be helpful to have this documented somewhere. 

```python
#!/usr/bin/env python
"""Builds a dataset given a hydra config file."""

try:
    import stackprinter

    stackprinter.set_excepthook(style="darkbg2")
except ImportError:
    pass  # no need to fail because of missing dev dependency

import os
os.environ['POLARS_MAX_THREADS'] = "1"

import dataclasses
from collections import defaultdict
from pathlib import Path
from typing import Any
```

**Comment by mmcdermott** [comment]
I've added some documentation to this effect in the README; it is not necessarily the most clearly delineated as of yet, but at least there is something there. Thanks for flagging this!
