### ISSUE TITLE
Running out of memory during build_event_and_measurement_dfs and polars dataset

### ISSUE THREAD

**Issue by juancq** [mmcdermott/EventStreamGPT#54]
I am running out of memory when running the build_dataset script with parquet input sources. Here is where I run out of memory: 

https://github.com/mmcdermott/EventStreamGPT/blob/5f20eaaf2b7b1896205a17d0e75b302d1a932a03/EventStream/data/dataset_base.py#L266-L282

With this being one of the likely culprits: 
https://github.com/mmcdermott/EventStreamGPT/blob/5f20eaaf2b7b1896205a17d0e75b302d1a932a03/EventStream/data/dataset_polars.py#L388-L392

Any suggestions on how this might be optimized?

**Comment by mmcdermott** [comment]
@juancq how much RAM does the running machine have? And I presume this is with limitations to the number of active threads, yes?

**Comment by juancq** [comment]
@mmcdermott the machine I'm using has 31GB of usable memory. I have two input sources. Input source 1 is a parquet of size 3.7GB (compressed) and input source 2 is a parquet of size 2.1 GB (compressed). I am using only five fields from input source 1 and five fields from input source 2. The total number of subjects is 9 million (median number of events per subject is 3). 

I can run the build_dataset script by limiting polars active threads and using about a third of the data and only input source 1. But with the two input sources and all the data (with or without streaming), it keeps crashing during build_event_and_measurement_dfs. 

The problem could be entirely Polars (with various current issues documenting memory issues). 

If you run https://github.com/mmcdermott/EventStreamGPT/blob/dev/sample_data/generate_synthetic_data.ipynb and change the number of subjects to 1 million or more, you might be able to replicate the issues I'm having. 

As a solution, I'm leaning towards running build_dataset separately on chunks of data, and then implementing a lazy pytorch dataloader pretraining a model that separately loads the cached DL representations from the separate build_dataset runs.

**Comment by mmcdermott** [comment]
Thanks for the additional information. I've had what sounds like similar
issues on some larger datasets and larger machines. Sharding the patients
is ultimately likely the way to fix the problem most reliably.

That said, in the interest of debugging, can you load up your two input
files in full in memory, or do they take up too much RAM to load all at
once? How much space do they take on disk if you save them in uncompressed
format? Even with streaming, Polaris still too aggressively tried to load
everything into memory, which may not be feasible on a 31GB machine.

**Comment by juancq** [comment]
@mmcdermott very good debugging idea! 

I cannot load (using read_parquet) either of the input source parquets by themselves. I run out of memory, so this is all on polars. This is without restricting which columns I load. 

If I load (using read_parquet) only the columns defined in the config file, I successfully load (1) the two input sources mentioned above and (2) all of the subjects input source into memory, using only about 56% of available memory. Memory usage is even lower (about 40%) if I use scan_parquet and then collect only the columns defined in the config file.

**Comment by mmcdermott** [comment]
Ok, so that suggests to me that there is likely some inefficient optimization of the polars queries going on, in which polars is trying to read in the full files prior to filtering down to only the requisite columns maybe? Or that some join is somehow blowing up memory even though it really shouldn't have that sort of effect. 

I encountered a similar issue recently in a different branch that required some more explicit management of the polars state to optimize, so I can try to apply similar logic here. Is your data publicly available @juancq, or private? It would help to have a realistic test case that is of a modest but non-trivial size so I can appropriate see how various changes impact the memory footprint. No pressure if it is not shareable, of course, just figured I'd check to make it easier to debug.

**Comment by juancq** [comment]
@mmcdermott The dataset is private, so I cannot share it. But I am making a modification of your synthetic data generation script that will be a good proxy for the data I have.

**Comment by mmcdermott** [comment]
No worries, @juancq -- feel free to not worry about the synthetic data generation example. Given the issue here is performance working with larger datasets or on smaller machines should give me enough to work with as a general rule, I just thought things would be more precise with the exact set-up you're working with.

**Comment by juancq** [comment]
@mmcdermott Here is a script that roughly simulates the dataset that I have. The columns generated in this script are the ones that I define in my config for building the dataset. 
[sample_data/generate_synthetic_hospital_admin_data.py
](https://github.com/juancq/EventStreamGPT/blob/0b85596124a1afe90e92d69ec687bcfa724dd842/sample_data/generate_synthetic_hospital_admin_data.py)

My actual dataset has about 100 other columns that I don't use (I didn't bother including 100 dummy string columns in the data generation script).

**Comment by mmcdermott** [comment]
This is great @juancq , thank you! Do you think it would be possible to make this script play double duty and add another block for generating an emergency file to simulate your issue with shared names across files from https://github.com/mmcdermott/EventStreamGPT/issues/53? As I commented in that issue, when I try to replicate it on my current synthetic data set-up, I don't have a problem with duplicate names, actually. Regardless I'll try to improve performance with this example for this issue proper. Thanks again!

**Comment by mmcdermott** [comment]
@juancq Is this still an issue? I'd like to close it if not so.
