### ISSUE TITLE
Misspelled measurement_configs in transformer/config.py

### ISSUE THREAD

**Issue by juancq** [mmcdermott/EventStreamGPT#72]
Attribute has been misspelled in transformer/config.py
Change to  measurement_configs. This is in dev branch. 
https://github.com/mmcdermott/EventStreamGPT/blob/900639e70091b5ce788a445631e5900b04d5f8b7/EventStream/transformer/config.py#L927-L927

**Comment by mmcdermott** [comment]
Sorry @juancq for the delay; I was traveling and missed this! Just pushed a fix.
